### ISSUE TITLE
Setting default distribution

### ISSUE THREAD

**Issue by nemofr** [mbl-35/wslctl#12]
With wslconfig, it's possible to define a default distribution. 

`wsl /s, /setdefault <DistributionName>`

It would be nice if it was possible to do that with wslctl in order to just type wsl to launch our favorite distribution.

**Comment by mbl-35** [comment]
Display the default distribution with ; 
```PS1
PS1> wslctl default 
ubuntu-20.04
```

Change default distribution to ubuntu-18.04:
```PS1
PS1> wslctl default ubuntu-18.04
* wsl default distribution set to Ubuntu-18.04
PS1> wslctl default 
ubuntu-18.04
```
